### PR TITLE
Refactor some classes

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Review by ppalaga — COMMENTED** [review]
Could you please explain what is the purpose of this refactoring?

**Comment by bennetelli** [comment]
* I renamed AbstractEditorconfigMojo to AbstractEditorConfigMojo with an upper C to be consistent to the rest of the codebase.
* Also rename CheckMojo and FormatMojo to EditorConfigCheckMojo and EditorConfigFormatMojo
* The other refactoring replaces a switch case with an if statement which improves the readability of the code

**Comment by ppalaga** [comment]
> * I renamed AbstractEditorconfigMojo to AbstractEditorConfigMojo with an upper C to be consistent to the rest of the codebase.

+1 for the consistency

> * Also rename CheckMojo and FormatMojo to EditorConfigCheckMojo and EditorConfigFormatMojo

I see what you do, but it would be nice to know why you think that longer names are better?

> * The other refactoring replaces a switch case with an if statement which improves the readability of the code

Ok, thanks, readability is a valid reason. The original might be more performant for this enum with five items thanks to being compiled using a tableswitch instruction.

**Comment by bennetelli** [comment]
"I see what you do, but it would be nice to know why you think that longer names are better?"

IMO it should be consistent as well. Both classes are extending AbstractEditorConfigMojo so they should have a name which shows these classes belong to each other even when you don't know the content of these classes.

**Comment by bennetelli** [comment]
"Ok, thanks, readability is a valid reason. The original might be more performant for this enum with five items thanks to being compiled using a tableswitch instruction."

Is a switch really more performant? I actually never thought about it. Then we could also leave it as it is right now.

**Comment by ppalaga** [comment]
> Is a switch really more performant? I actually never thought about it. Then we could also leave it as it is right now.

Yes, I'd say so. It is less instructions for the second and all following items.

**Comment by bennetelli** [comment]
Just reverted the switch/if statement changes.

**Comment by ppalaga** [comment]
Thanks for the contribution and thanks for the patience with the review!

**Comment by bennetelli** [comment]
You're welcome! And thanks to you as well :)

**Pull request merged**
