### PR TITLE
Maven 3.9.0 fixes

### PR DESCRIPTION
**Pull request by glhez**
Hello,

Since Maven 3.9.0, plexus-utils is no longer shipped in the classpath: https://issues.apache.org/jira/browse/MNG-6965

This cause error when executing the plugin:

```
[ERROR] Failed to execute goal org.ec4j.maven:editorconfig-maven-plugin:0.1.1:check (editorconfig-check-execution) on project maven-parent: Execution editorconfig-check-execution of goal org.ec4j.maven:editorconfig-maven-plugin:0.1.1:check failed: A required class was missing while executing org.ec4j.maven:editorconfig-maven-plugin:0.1.1:check: org/codehaus/plexus/util/DirectoryScanner
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.ec4j.maven:editorconfig-maven-plugin:0.1.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/E:/apps/data/maven/local/org/ec4j/maven/editorconfig-maven-plugin/0.1.1/editorconfig-maven-plugin-0.1.1.jar
[ERROR] urls[1] = file:/E:/apps/data/maven/local/org/ec4j/linters/editorconfig-lint-api/0.2.1/editorconfig-lint-api-0.2.1.jar
[ERROR] urls[2] = file:/E:/apps/data/maven/local/org/ec4j/core/ec4j-core/0.2.1/ec4j-core-0.2.1.jar
[ERROR] urls[3] = file:/E:/apps/data/maven/local/org/ec4j/linters/editorconfig-linters/0.2.1/editorconfig-linters-0.2.1.jar
[ERROR] urls[4] = file:/E:/apps/data/maven/local/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------
```

The pull request adapt the plugin to use the "latest" version of most dependencies:

- I changed the version to 0.2.0 due to maven 3.9.0
- the maven wrapper is switched to 3.9.0 https://maven.apache.org/wrapper/
- I fixed the deprecated use of licenceHeader / excludes of mycyla licence plugin
- impsort-maven-plugin have the same issue
- I removed some code related to Java 7 since Maven 3.9 is JDK8 only.
 
If the PR is to complex to merge, the minimal change is to

1) use Maven 3.9.0 for building and testing
2) introduce the dependency in editorconfig-maven-plugin/pom.xml 

Eg:
```
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
    </dependency>
```

Without a fix, the issue can be fixed per project by adding the following dependency to the plugin:

```
        <plugin> <groupId>org.ec4j.maven</groupId>          <artifactId>editorconfig-maven-plugin</artifactId>                 <version>${plg.editorconfig.version}</version>
          <dependencies>
            <dependency> <groupId>org.codehaus.plexus</groupId> <artifactId>plexus-utils</artifactId> <version>3.0.17</version> </dependency>
          </dependencies>
        </plugin>
```

### CODE REVIEW

**Comment by ppalaga** [comment]
Thanks @glhez, I created https://github.com/ec4j/editorconfig-maven-plugin/pull/69 with one additional commit to see whether it will pass on Linux at least.

**Comment by Tockra** [comment]
What is the current state here?

**Comment by ppalaga** [comment]
Sorry for the delay, I did some work to fix the CI, but did not have enough time to finish. Any help would be welcome.

**Comment by ppalaga** [comment]
Thanks for your pro-activity and bugging me. I was able to fix all issues in https://github.com/ec4j/editorconfig-maven-plugin/pull/69

**Pull request closed without merging**
